//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontwiseRecruitingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public int ID { get; set; }
        public string SearchID { get; set; }
        public string UserID { get; set; }
        public string SearchLabel { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string GroupID { get; set; }
    }
}
