//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontwiseRecruitingApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class searchwiser_dbEntities1 : DbContext
    {
        public searchwiser_dbEntities1()
            : base("name=searchwiser_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<SearchStringsCategory> SearchStringsCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WordsCategory> WordsCategories { get; set; }
        public virtual DbSet<SearchHistory> SearchHistories { get; set; }
        public virtual DbSet<UsersSaved> UsersSaveds { get; set; }
    }
}
