//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontwiseRecruitingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Role { get; set; }
        public string Position { get; set; }
        public int ID { get; set; }
        public string email { get; set; }
        public string user_password { get; set; }
        public Nullable<int> Points { get; set; }
        public string profile_photo_url { get; set; }
    }
}
