//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontwiseRecruitingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordsCategory
    {
        public int ID { get; set; }
        public string Word { get; set; }
        public string CategoryID { get; set; }
        public string WordsGroup { get; set; }
        public Nullable<bool> Available { get; set; }
        public string PostedBy { get; set; }
    }
}
